//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ali_Amir_Filters.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Candel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candel()
        {
            this.Filterssses = new HashSet<Filtersss>();
        }
    
        public short id { get; set; }
        [Required]
        [DisplayName("الاسم")]
        [MaxLength(50)]
        public string Name { get; set; }
        [Required]
        [DisplayName("رقم الشمعه")]
        [MaxLength(2)]
        public short Candel_date { get; set; }
        [Required]
        [DisplayName("السعر")]
        [MaxLength(6)]
        public decimal price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filtersss> Filterssses { get; set; }
    }
}
