//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ali_Amir_Filters.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Coustmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coustmer()
        {
            this.syanas = new HashSet<syana>();
            this.accountances = new HashSet<accountance>();
            this.Syana_history = new HashSet<Syana_history>();
        }
    
        public int Id { get; set; }
        [Required]
        [DisplayName("الاسم")]
        [MaxLength(50)]
        public string Name { get; set; }
        [Required]
        [DisplayName("العنوان")]
        [MaxLength(250)]
        public string adress { get; set; }
        [Required]
        [DisplayName("رقم الفون")]
        [MaxLength(13)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered CONTACT_NUMBER format is not valid.")]
        public string phone_Number { get; set; }
        
        [DisplayName("رقم الفون 2")]
        [MaxLength(13)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered CONTACT_NUMBER format is not valid.")]
        public string phone_Number2 { get; set; }
        [Required]
        [DisplayName("تاريخ التركيب")]

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public System.DateTime Dates { get; set; }
        public int Filter_id { get; set; }
        [Required]
        [DisplayName("المنطقه")]
        [MaxLength(80)]
        public string area { get; set; }
    
        public virtual Filtersss Filtersss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syana> syanas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accountance> accountances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Syana_history> Syana_history { get; set; }
    }
}
