//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ali_Amir_Filters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ali_AmirEntities : DbContext
    {
        public Ali_AmirEntities()
            : base("name=Ali_AmirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candel> Candels { get; set; }
        public virtual DbSet<Filtersss> Filterssses { get; set; }
        public virtual DbSet<syana> syanas { get; set; }
        public virtual DbSet<Coustmer> Coustmers { get; set; }
        public virtual DbSet<accountance> accountances { get; set; }
        public virtual DbSet<Syana_history> Syana_history { get; set; }
    
        public virtual ObjectResult<get_monthss_Result> get_monthss(Nullable<int> filt_id)
        {
            var filt_idParameter = filt_id.HasValue ?
                new ObjectParameter("filt_id", filt_id) :
                new ObjectParameter("filt_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_monthss_Result>("get_monthss", filt_idParameter);
        }
    
       
    
        public virtual ObjectResult<get_new_syanas_Result> get_new_syanas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_new_syanas_Result>("get_new_syanas");
        }
    
        public virtual ObjectResult<get_new_syanas2_Result> get_new_syanas2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_new_syanas2_Result>("get_new_syanas2");
        }
    
        public virtual ObjectResult<get_new_syanas1_Result> get_new_syanas1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_new_syanas1_Result>("get_new_syanas1");
        }
    
        public virtual ObjectResult<syana_table_Result> syana_table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<syana_table_Result>("syana_table");
        }
    
        public virtual ObjectResult<syana_table2_Result> syana_table2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<syana_table2_Result>("syana_table2");
        }
    
        public virtual ObjectResult<syana_table3_Result> syana_table3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<syana_table3_Result>("syana_table3");
        }
    
        public virtual ObjectResult<Accountance_sum_Result> Accountance_sum(Nullable<int> acc_year, Nullable<int> acc_month, string acc_type)
        {
            var acc_yearParameter = acc_year.HasValue ?
                new ObjectParameter("acc_year", acc_year) :
                new ObjectParameter("acc_year", typeof(int));
    
            var acc_monthParameter = acc_month.HasValue ?
                new ObjectParameter("Acc_month", acc_month) :
                new ObjectParameter("Acc_month", typeof(int));
    
            var acc_typeParameter = acc_type != null ?
                new ObjectParameter("acc_type", acc_type) :
                new ObjectParameter("acc_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Accountance_sum_Result>("Accountance_sum", acc_yearParameter, acc_monthParameter, acc_typeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sum_acc(Nullable<int> acc_month, Nullable<int> acc_year, string acc_type)
        {
            var acc_monthParameter = acc_month.HasValue ?
                new ObjectParameter("acc_month", acc_month) :
                new ObjectParameter("acc_month", typeof(int));
    
            var acc_yearParameter = acc_year.HasValue ?
                new ObjectParameter("acc_year", acc_year) :
                new ObjectParameter("acc_year", typeof(int));
    
            var acc_typeParameter = acc_type != null ?
                new ObjectParameter("acc_type", acc_type) :
                new ObjectParameter("acc_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sum_acc", acc_monthParameter, acc_yearParameter, acc_typeParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> accountance_summary(Nullable<int> date_month, Nullable<int> date_year, string acc_type)
        {
            var date_monthParameter = date_month.HasValue ?
                new ObjectParameter("date_month", date_month) :
                new ObjectParameter("date_month", typeof(int));
    
            var date_yearParameter = date_year.HasValue ?
                new ObjectParameter("date_year", date_year) :
                new ObjectParameter("date_year", typeof(int));
    
            var acc_typeParameter = acc_type != null ?
                new ObjectParameter("acc_type", acc_type) :
                new ObjectParameter("acc_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("accountance_summary", date_monthParameter, date_yearParameter, acc_typeParameter);
        }
    
        public virtual ObjectResult<sp_syana_history_Result> sp_syana_history(Nullable<int> cous_id)
        {
            var cous_idParameter = cous_id.HasValue ?
                new ObjectParameter("cous_id", cous_id) :
                new ObjectParameter("cous_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_syana_history_Result>("sp_syana_history", cous_idParameter);
        }
    
        public virtual ObjectResult<sp_syana_history2_Result> sp_syana_history2(Nullable<int> cous_id)
        {
            var cous_idParameter = cous_id.HasValue ?
                new ObjectParameter("cous_id", cous_id) :
                new ObjectParameter("cous_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_syana_history2_Result>("sp_syana_history2", cous_idParameter);
        }
    
        public virtual ObjectResult<sp_history_Result> sp_history(Nullable<int> cous_id)
        {
            var cous_idParameter = cous_id.HasValue ?
                new ObjectParameter("cous_id", cous_id) :
                new ObjectParameter("cous_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_history_Result>("sp_history", cous_idParameter);
        }
    
        public virtual ObjectResult<sp_history6_Result> sp_history6(Nullable<int> cous_id)
        {
            var cous_idParameter = cous_id.HasValue ?
                new ObjectParameter("cous_id", cous_id) :
                new ObjectParameter("cous_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_history6_Result>("sp_history6", cous_idParameter);
        }
    }
}
