//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ali_Amir_Filters.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class syana
    {
        public int Id { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public System.DateTime date_syana { get; set; }
        public int customer_id { get; set; }
        public string candel_name { get; set; }
        public string filter_name { get; set; }
        public bool is_done { get; set; }
        public Nullable<int> months_late { get; set; }
        public Nullable<int> number_of_months { get; set; }
    
        public virtual Coustmer Coustmer { get; set; }
    }
}
